################ English language ##################
[en]
languageName = "En"
languageCode = "en-us"
contentDir = "content/english"
weight = 1

################ Russian language ##################
[ru]
languageName = "Ru"
languageCode = "ru-ru"
contentDir = "content/russian"
weight = 2
